packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

overrides:
  micromatch@<4.0.8: '>=4.0.8'
  tmp@<=0.2.3: '>=0.2.4'
